# This is the matrix copied from 3.x
# Each components needs to be gradually enabled as 
# the core and libraries support them

sketch:
  - extras/arduino-examples/examples/01.Basics/BareMinimum/BareMinimum.ino
  - extras/arduino-examples/examples/01.Basics/Blink/Blink.ino
  - extras/arduino-examples/examples/01.Basics/DigitalReadSerial/DigitalReadSerial.ino
  - extras/arduino-examples/examples/01.Basics/AnalogReadSerial/AnalogReadSerial.ino
  - extras/arduino-examples/examples/01.Basics/Fade/Fade.ino
  - extras/arduino-examples/examples/02.Digital/BlinkWithoutDelay/BlinkWithoutDelay.ino
  - extras/arduino-examples/examples/02.Digital/Button/Button.ino
  - extras/arduino-examples/examples/02.Digital/Debounce/Debounce.ino
  - extras/arduino-examples/examples/02.Digital/DigitalInputPullup/DigitalInputPullup.ino
  - extras/arduino-examples/examples/02.Digital/StateChangeDetection/StateChangeDetection.ino
  - extras/arduino-examples/examples/02.Digital/toneKeyboard/toneKeyboard.ino
  - extras/arduino-examples/examples/02.Digital/toneMelody/toneMelody.ino
  - extras/arduino-examples/examples/02.Digital/toneMultiple/toneMultiple.ino
  - extras/arduino-examples/examples/02.Digital/tonePitchFollower/tonePitchFollower.ino
  - extras/arduino-examples/examples/03.Analog/AnalogInOutSerial/AnalogInOutSerial.ino
  - extras/arduino-examples/examples/03.Analog/AnalogInput/AnalogInput.ino 
  - extras/arduino-examples/examples/03.Analog/Calibration/Calibration.ino
  - extras/arduino-examples/examples/03.Analog/Fading/Fading.ino
  - extras/arduino-examples/examples/03.Analog/Smoothing/Smoothing.ino
  - extras/arduino-examples/examples/04.Communication/ASCIITable/ASCIITable.ino
  # - extras/arduino-examples/examples/04.Communication/MultiSerial/MultiSerial.ino
  # - extras/arduino-examples/examples/04.Communication/PhysicalPixel/PhysicalPixel.ino
  # - extras/arduino-examples/examples/04.Communication/SerialEvent/SerialEvent.ino
  - extras/arduino-examples/examples/05.Control/ForLoopIteration/ForLoopIteration.ino

fqbn:
  - infineon:xmc:kit_xmc11_boot_001
  - infineon:xmc:kit_xmc13_boot_001
  - infineon:xmc:kit_xmc1400_arduino
  - infineon:xmc:kit_xmc14_2go
  - infineon:xmc:kit_xmc47_relax
  - infineon:xmc:kit_xmc_2go_xmc1100_v1
  - infineon:xmc:kit_xmc_plt2go_xmc4200
  - infineon:xmc:kit_xmc_plt2go_xmc4400

# sketch:
#     - libraries/LED
#     - libraries/RTC/examples/SimpleRTC
#     - libraries/SPI
#     - libraries/Wire
#     - libraries/DeviceControlXMC/examples/DieTemperatureMeasurement/DieTemperatureMeasurement.ino
#     - libraries/DeviceControlXMC/examples/HeapMemoryMeasurement/HeapMemoryMeasurement.ino
#     - libraries/DeviceControlXMC/examples/StackMemoryMeasurement/StackMemoryMeasurement.ino

# include: 
#   - fqbn: infineon:xmc:kit_xmc11_boot_001
#     sketch:
#       - libraries/I2S
#       - libraries/DeviceControlXMC/examples/SleepModeXMC1100/SleepModeXMC1100.ino
#   - fqbn: infineon:xmc:kit_xmc_2go_xmc1100_v1
#     sketch: 
#       - libraries/I2S
#       - libraries/DeviceControlXMC/examples/SleepModeXMC1100/SleepModeXMC1100.ino
#   - fqbn: infineon:xmc:kit_xmc13_boot_001
#     sketch: 
#       - libraries/DeviceControlXMC/examples/SleepModeXMC1100/SleepModeXMC1100.ino
#   - fqbn: infineon:xmc:kit_xmc14_2go
#     sketch:
#       - libraries/I2S
#       - libraries/DeviceControlXMC/examples/SleepModeXMC1100/SleepModeXMC1100.ino
#       - libraries/CAN
#   - fqbn: infineon:xmc:kit_xmc1400_arduino
#     sketch:
#       - libraries/DeviceControlXMC/examples/SleepModeXMC1100/SleepModeXMC1100.ino
#   - fqbn: infineon:xmc:kit_xmc_plt2go_xmc4200
#     sketch: 
#       - libraries/RTC/examples/AlarmRTC/AlarmRTC.ino
#       - libraries/CAN
#   - fqbn: infineon:xmc:kit_xmc_plt2go_xmc4400
#     sketch: 
#       - libraries/CAN
#   - fqbn: infineon:xmc:kit_xmc47_relax
#     sketch: 
#       - libraries/I2S
#       - libraries/DeviceControlXMC/examples/SleepModeXMC4700/SleepModeXMC4700.ino
#       - libraries/DMA
#       - libraries/RTC/examples/AlarmRTC/AlarmRTC.ino
#       - libraries/CAN

# exclude: 
#   - fqbn: infineon:xmc:kit_xmc14_2go
#     sketch:
#       - libraries/DeviceControlXMC/examples/StackMemoryMeasurement/StackMemoryMeasurement.ino
#   - fqbn: infineon:xmc:kit_xmc1400_arduino
#     sketch:
#       - libraries/DeviceControlXMC/examples/StackMemoryMeasurement/StackMemoryMeasurement.ino
#   - fqbn: infineon:xmc:kit_xmc_plt2go_xmc4200
#     sketch: 
#       - libraries/DeviceControlXMC/examples/DieTemperatureMeasurement/DieTemperatureMeasurement.ino
#       - libraries/DeviceControlXMC/examples/HeapMemoryMeasurement/HeapMemoryMeasurement.ino
#   - fqbn: infineon:xmc:kit_xmc_plt2go_xmc4400
#     sketch: 
#       - libraries/DeviceControlXMC/examples/DieTemperatureMeasurement/DieTemperatureMeasurement.ino
#       - libraries/DeviceControlXMC/examples/HeapMemoryMeasurement/HeapMemoryMeasurement.ino
