### Build commands


### Example program
## XMC4700_Relax_Kit
make FQBN=Infineon:xmc:XMC4700_Relax_Kit PORT=COM20 CANReceiver flash monitor

make FQBN=Infineon:xmc:XMC4700_Relax_Kit PORT=COM20 CANReceiverCallback flash monitor

make FQBN=Infineon:xmc:XMC4700_Relax_Kit PORT=COM24 CANSender flash monitor

make FQBN=Infineon:xmc:XMC4700_Relax_Kit PORT=COM24 CANLoopBack flash monitor

## XMC1400_XMC2GO
make FQBN=Infineon:xmc:XMC1400_XMC2GO PORT=COM41 CANReceiver flash monitor

make FQBN=Infineon:xmc:XMC1400_XMC2GO PORT=COM41 CANReceiverCallback flash monitor

make FQBN=Infineon:xmc:XMC1400_XMC2GO PORT=COM42 CANSender flash monitor

make FQBN=Infineon:xmc:XMC1400_XMC2GO PORT=COM42 CANLoopBack flash monitor


### Unit tests
make FQBN=Infineon:xmc:XMC4700_Relax_Kit PORT=COM20 CAN monitor

make FQBN=Infineon:xmc:XMC1100_XMC2GO PORT=COM21 CAN_connected monitor
